services:
  api-antrian:
    container_name: api-adameds-antrian
    build:
      context: ./
      dockerfile: Dockerfile
    image: adameds/antrian:dev
    ports:
      - 7001:7001
    restart: always
    environment:
      INFISICAL_TOKEN: ${INFISICAL_TOKEN}
      APPLICATION_HOST: ${APPLICATION_HOST}
      APPLICATION_PORT: ${APPLICATION_PORT}
      ADMISI_API_URL: ${ADMISI_API_URL}
      ADMISI_SECRET_KEY: ${ADMISI_SECRET_KEY}
      ANTRIAN_KEY_SECRET: ${ANTRIAN_KEY_SECRET}
    networks:
      - antrian-bridge
networks:
  antrian-bridge:
    driver: bridge
